### ISSUE TITLE
Kan je project niet openen

### ISSUE THREAD

**Issue by joelle78** [rosahoffer/your-tribe-for-life-profile-card#1]
<img width="424" alt="Scherm­afbeelding 2023-09-15 om 14 44 00" src="https://github.com/rosahoffer/your-tribe-for-life-profile-card/assets/96306220/4cb692fa-b7df-4ca7-9f73-2e0d5c378bf5">

**Comment by rosahoffer** [comment]
Ik weet niet wat ik daar aan moet doen, Maar ik logisch ook ik ben ook niet te vertrouwen XD
